spring:
    datasource:
        url: jdbc:h2:C:\Users\logonrmlocal\Desktop\git\library-batch;DB_CLOSE_ON_EXIT=FALSE
        username: fiap
        password: fiap


file:
    path: 'C:\Users\logonrmlocal\Desktop\git\library-batch\teste.txt'